### ISSUE TITLE
Establish protocol for (developing, maintaining) parallel prototype-format-models

### ISSUE THREAD

**Issue by jcruzaxaeon** [jcruzaxaeon/voli#1]
## TODO
*Lorem ipsum* dolor sit amet.
- [x] (Discuss, Establish) a protocol for maintaining separate prototype-formats (in separate documents?) from which we can model the live `voli` file.
- [x] Add protocol to `readme.md`

## Emoji Support
Use an "emojiCode" surrounded by colons (`:`). I doubt this will be needed.
```
:emojiCode:
```
- See [Emoji Hintsheet](https://www.webfx.com/tools/emoji-cheat-sheet/)
- :t-rex: :cat: :bear:

## (In-Issue User-Notifications / Mentions?)
This might also be called a "Mention".  I am almost certain that the leading "cc" is not needed for full "Mention" functionality.
- cc @jcruzaxaeon
- cc @NekoHuchu 
- [x] Does the "Mention" mechanism send an in-GitHub email?
   - Yes.  GitHub notification sent to NekoHuchu with @ format `Mention`
